version: '3.9'
services:

  postgres-db:
    image: arm32v7/postgres:16  # Imagen compatible con Raspberry Pi 3
    restart: always
    container_name: postgres_db
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: DockerFile.deploy  # Verifica que el nombre esté correcto
    container_name: nest-app
    environment:
      - NODE_PORT=${NODE_PORT}
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    depends_on:
      - postgres-db
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
