version: '3.9'
services:

  postgres-db:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: nest-app
    environment:
      - NODE_PORT=${NODE_PORT}
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    depends_on:
      - postgres-db
    volumes:
      - ./src:/app/src
volumes:
  pgdata:
